<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KubeJob.Client\KubeJob.Client.csproj" />
    <ProjectReference Include="..\KubeJob.Server\KubeJob.Server.csproj" />
    <ProjectReference Include="..\KubeJob.Worker\KubeJob.Worker.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>KubeJob Meta-Package. Includes client, control plane, and worker hosting for unified applications.</Description>
  </PropertyGroup>

</Project>
