<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KubeJob\KubeJob.csproj" />
    <ProjectReference Include="..\KubeJob.Sample.RemoteWorker\KubeJob.Sample.RemoteWorker.csproj" />
  </ItemGroup>

</Project>
